# Autogenerated wrapper script for UASM_jll for x86_64-linux-musl
export uasm

JLLWrappers.@generate_wrapper_header("UASM")
JLLWrappers.@declare_executable_product(uasm)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        uasm,
        "bin/uasm",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
